
export enum Tool {
  CODE_GENERATOR = 'CODE_GENERATOR',
  CODE_REFACTOR = 'CODE_REFACTOR',
  TEST_GENERATOR = 'TEST_GENERATOR',
  DOC_WRITER = 'DOC_WRITER',
  CHANGELOG_GENERATOR = 'CHANGELOG_GENERATOR',
}
